#!/bin/bash

# Funciona apenas apartir de qualquer distro baseada no ubuntu 22.04 pra cima.

echo "=============================="
echo " Bem-vindo ao Auto-Palera1n16 "
echo "=============================="
echo "Voce escolheu o iOS $1"
echo "Digite 1 para iniciar ou 0 para sair"
read resp
if [ $resp -eq 1 ]
 then
   echo -e "\033[0;37m[*] Instalando Dependencias... pode demorar em torno de 1 hora, aguarde com paciencia!"
   sudo apt-get -o Acquire::Check-Valid-Until=false -o Acquire::Check-Date=false update
   sudo apt update
   sudo apt install git -y
   sudo apt-get install sudo gcc bash wget python3-pip libavahi-client-dev libusb-1.0-0 libusb-1.0-0-dev libadolc2 libusbmuxd-tools libtool usbmuxd libtool-bin autoconf automake libimobiledevice* make -y
   sudo pip install pyimg4
   wget https://github.com/Italogc/Auto-Palera1n16/raw/main/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
   wget https://github.com/CoocooFroggy/FutureRestore-GUI/releases/download/v1.98.2/FutureRestore-GUI-Debian-1.98.2.deb
   sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
   sudo dpkg -i FutureRestore-GUI-Debian-1.98.2.deb
   sudo git clone https://github.com/tihmstar/libgeneral
   cd libgeneral
   printf "\n[*] Compilando LIBGENERAL...\n\n"
   sudo ./autogen.sh
   sudo make
   sudo make install
   cd ..
   sudo git clone https://github.com/tihmstar/usbmuxd2
   cd usbmuxd2
   printf "\n[*] Compilando USBMUXD2...\n\n"
   sudo ./autogen.sh
   sudo make
   sudo make install
   cd ..
   sudo apt-get update
   sudo apt-get install build-essential
   sudo apt-get install pkg-config
   sudo apt-get install checkinstall
   sudo apt-get install git
   sudo apt-get install autoconf 
   sudo apt-get install automake
   sudo apt-get install libtool-bin
   sudo apt-get install libplist-dev
   sudo apt-get install libusbmuxd-dev
   sudo apt-get install libssl-dev
   sudo apt-get install usbmuxd
   sudo apt-get install doxygen
   sudo apt-get install cython
   printf "\n[*] A instalar dependências do LibiMobileDevice...\n"
   sudo git clone https://github.com/libimobiledevice/libimobiledevice.git
   cd libimobiledevice
   sudo ./autogen.sh
   sudo make
   sudo make install
   sudo ./autogen.sh --prefix=/opt/local --enable-debug
   sudo make
   sudo make install
   sudo ./autogen.sh --prefix=/opt/local --enable-debug
   sudo make
   sudo make install
   sudo ./autogen.sh --with-gnutls
   sudo ./autogen.sh --with-mbedtls mbedtls_INCLUDES=/opt/local/include mbedtls_LIBDIR=/opt/local/lib
   cd ..
   printf "\n[*] A instalar dependências avançadas do usbmuxd2...\n"
   sudo git clone --recursive https://github.com/Italogc/usbmuxd2
   sudo apt-get update
   sudo add-apt-repository universe
   sudo apt-get update
   sudo apt install git curl python3-pip -y
   printf "\n[*] Dependencias instaladas!\n"
   sleep 1
   systemctl stop usbmuxd
   cd ..
   echo -e "\n[*] Baixando Palera1n...\n"
   sudo git clone --recursive https://github.com/palera1n/palera1n -b legacy
   echo "[+] Palera1n Baixado!"
   sudo git clone --recursive https://github.com/Italogc/palera1n-3.0
   echo "[+] Palera1n Boot Fix 3.0 de Italogc-iOS Baixado!"
   echo "[+]                "
   echo "[+] Prosseguindo para o Palera1n Jailbreak..."
   echo "[+]                "
   printf "\033[1;37m[*] Conecte seu aparelho em modo dfu e digite os comandos abaixo\n"
   printf "\n\033[0;32mcd palera1n\n"
   printf "\033[0;32msudo ./palera1n.sh --tweaks $1\n\n"
else
   echo "[*] Saindo..."
   exit
fi
